name: Build and verify

on:
  push:
    branches:
      - '**'
      - '!main'

permissions:
  contents: read
  security-events: write

jobs:
  build-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and verify CDK infrastructure
        uses: ./.github/actions/build-verify-infrastructure

      - name: Run Checkov scan
        uses: ./.github/actions/run-checkov-scan
