name: Build and verify

on:
  push:
    branches:
      - '**'
      - '!main'

permissions:
  contents: read
  id-token: write

jobs:
  build-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
        working-directory: infrastructure

      - name: Check formatting
        run: |
          npm run format-check
        working-directory: infrastructure

      - name: Lint
        run: |
          npm run lint
        working-directory: infrastructure

      - name: Compile Typescript
        run: |
          npm run build
        working-directory: infrastructure

      - name: Unit tests
        run: |
          npm test
        working-directory: infrastructure
